In [1]:
from math import degrees
from socket import setdefaulttimeout
from turtle import pos
from mitsubishi import MITSUBISHI
import rospy
from robot_base import Robot
import numpy as np
from scipy.spatial.transform import Rotation as R
from multiprocessing import Process, Array



In [10]:

rot_mat = R.from_euler('zyx', [90, 0, 180], degrees=True).as_matrix()
print(rot_mat)

[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -2.22044605e-16 -1.22464680e-16]
 [ 1.22464680e-16  2.46519033e-32 -1.00000000e+00]]


In [8]:

rot_mat = R.from_euler('XYZ', [180, 0, 90], degrees=True).as_matrix()
print(rot_mat)

[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -2.22044605e-16 -1.22464680e-16]
 [ 1.22464680e-16  2.46519033e-32 -1.00000000e+00]]


In [1]:
from math import degrees
from socket import setdefaulttimeout
from turtle import pos
from mitsubishi import MITSUBISHI
import rospy
from robot_base import Robot
import numpy as np
from scipy.spatial.transform import Rotation as R
from multiprocessing import Process, Array


In [2]:


robot = MITSUBISHI('192.168.0.20')



robot.activate_control(True)
robot.activate_servo(True)
robot.start_program()

In [3]:
robot.execute('J10 = (0.0, 0.0, 90.0, 0.0, 0.0, 0.0)')
robot.execute('MOV J10')